RPTRST
 'BASIC=2' 
  PRESSURE  SGAS  SOIL  SWAT  XMF  YMF 
  DENG DENO DENW 
  VGAS VOIL VWAT
  RS RV BO BG BW
  KRG KRO KRW  
  PCOW PCOG
/

-- Start water injection after 0 years
WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days  
30.5 30.5 30.25
/

WELOPEN
 'INJW' 'OPEN' /
 'INJG' 'SHUT' /
/
TSTEP
--Advance the simulater 91.25 days 
30.5 30.5 30.25
/


WELOPEN
 'INJW' 'SHUT' /
 'INJG' 'OPEN' /
/

TSTEP
--Advance the simulater 91.25 days + 4 leap days 
30.5 30.5 34.25
/
-- End simulation after 20 years

END


